blank_issues_enabled: false
contact_links:
  - name: è³ªå•ãƒ»ç›¸è«‡
    url: https://twitter.com/ei2537
    about: ãƒã‚°å ±å‘Šã‚„æ©Ÿèƒ½ãƒªã‚¯ã‚¨ã‚¹ãƒˆä»¥å¤–ã®è³ªå•ãƒ»ç›¸è«‡ã¯Xã®DMã«ã¦å—ã‘ä»˜ã‘ã¾ã™ã€‚

defaults:
  - template: "bug_report.yml"
    name: "ğŸ› ãƒã‚°å ±å‘Š"
    about: "ãƒã‚°ã‚’å ±å‘Šã™ã‚‹"
  - template: "feature_request.yml"
    name: "ğŸ’¡ è§£ç­”ä¿®æ­£"
    about: "å•é¡Œã®è§£ç­”ã®ä¿®æ­£"
